INSERT INTO IFS_DATA_DIC (ID, DATA_TYPE_NO, DATA_NO, DATA_TYPE_NAME, DATA_NO_LEN, DATA_NAME, LIMIT_FLAG, HIGH_LIMIT, LOW_LIMIT, MISCFLGS) VALUES ('IFSBAT001', '110', '0', '多分行并行标志', 1, '0－无', '1', '0', '0', null);
INSERT INTO IFS_DATA_DIC (ID, DATA_TYPE_NO, DATA_NO, DATA_TYPE_NAME, DATA_NO_LEN, DATA_NAME, LIMIT_FLAG, HIGH_LIMIT, LOW_LIMIT, MISCFLGS) VALUES ('IFSBAT002', '110', '1', '多分行并行标志', 1, '1－有', '1', '0', '0', null);
INSERT INTO IFS_DATA_DIC (ID, DATA_TYPE_NO, DATA_NO, DATA_TYPE_NAME, DATA_NO_LEN, DATA_NAME, LIMIT_FLAG, HIGH_LIMIT, LOW_LIMIT, MISCFLGS) VALUES ('IFSBAT003', '111', '0', '临时取消标志', 1, '0－不临时取消', '1', '0', '0', null);
INSERT INTO IFS_DATA_DIC (ID, DATA_TYPE_NO, DATA_NO, DATA_TYPE_NAME, DATA_NO_LEN, DATA_NAME, LIMIT_FLAG, HIGH_LIMIT, LOW_LIMIT, MISCFLGS) VALUES ('IFSBAT004', '111', '1', '临时取消标志', 1, '1－临时取消', '1', '0', '0', null);
INSERT INTO IFS_DATA_DIC (ID, DATA_TYPE_NO, DATA_NO, DATA_TYPE_NAME, DATA_NO_LEN, DATA_NAME, LIMIT_FLAG, HIGH_LIMIT, LOW_LIMIT, MISCFLGS) VALUES ('IFSBAT005', '112', '0', '是否出错忽略标志', 1, '0－出错不可忽略', '1', '0', '0', null);
INSERT INTO IFS_DATA_DIC (ID, DATA_TYPE_NO, DATA_NO, DATA_TYPE_NAME, DATA_NO_LEN, DATA_NAME, LIMIT_FLAG, HIGH_LIMIT, LOW_LIMIT, MISCFLGS) VALUES ('IFSBAT006', '112', '1', '是否出错忽略标志', 1, '1－出错忽略', '1', '0', '0', null);
INSERT INTO IFS_DATA_DIC (ID, DATA_TYPE_NO, DATA_NO, DATA_TYPE_NAME, DATA_NO_LEN, DATA_NAME, LIMIT_FLAG, HIGH_LIMIT, LOW_LIMIT, MISCFLGS) VALUES ('IFSBAT007', '113', '0', '单独启动标志', 1, '0－不可单独启动', '1', '0', '0', null);
INSERT INTO IFS_DATA_DIC (ID, DATA_TYPE_NO, DATA_NO, DATA_TYPE_NAME, DATA_NO_LEN, DATA_NAME, LIMIT_FLAG, HIGH_LIMIT, LOW_LIMIT, MISCFLGS) VALUES ('IFSBAT008', '113', '1', '单独启动标志', 1, '1－可单独启动', '1', '0', '0', null);

INSERT INTO IFS_MENU_INF (FUNCID, FUNCNAME, PAGEPATH, LOCATION, ISDIRECTORY, LASTDIRECTORY, SHOWSEQ, FUNC_CLASS, FUNC_TYPE, WORKFLOW_FLAG, UP_FUNC_CODE, FUNC_DESC, STATUS, MISCFLGS, MISC, ICON_CLS) VALUES ('1004', '批量管理', null, 2, 0, null, 4, null, '0', null, null, null, null, null, null, 'fa fa-tasks');
INSERT INTO IFS_MENU_INF (FUNCID, FUNCNAME, PAGEPATH, LOCATION, ISDIRECTORY, LASTDIRECTORY, SHOWSEQ, FUNC_CLASS, FUNC_TYPE, WORKFLOW_FLAG, UP_FUNC_CODE, FUNC_DESC, STATUS, MISCFLGS, MISC, ICON_CLS) VALUES ('100401', '工作日期维护', '/pages/mng/holidayMng.jsp', 2, 0, '1004', 1, null, '0', null, null, null, null, null, null, 'fa fa-calendar');
INSERT INTO IFS_MENU_INF (FUNCID, FUNCNAME, PAGEPATH, LOCATION, ISDIRECTORY, LASTDIRECTORY, SHOWSEQ, FUNC_CLASS, FUNC_TYPE, WORKFLOW_FLAG, UP_FUNC_CODE, FUNC_DESC, STATUS, MISCFLGS, MISC, ICON_CLS) VALUES ('100402', '批量参数设置', '/pages/batch/BatchMngTab.jsp', 2, 0, '1004',2, null, '0', null, null, null, null, null, null, 'fa fa-terminal');
INSERT INTO IFS_MENU_INF (FUNCID, FUNCNAME, PAGEPATH, LOCATION, ISDIRECTORY, LASTDIRECTORY, SHOWSEQ, FUNC_CLASS, FUNC_TYPE, WORKFLOW_FLAG, UP_FUNC_CODE, FUNC_DESC, STATUS, MISCFLGS, MISC, ICON_CLS) VALUES ('100403', '批量总控监控', '/pages/batch/BatchExcute.jsp', 2, 0, '1004', 3, null, '0', null, null, null, null, null, null, 'fa fa-microchip');
INSERT INTO IFS_MENU_INF (FUNCID, FUNCNAME, PAGEPATH, LOCATION, ISDIRECTORY, LASTDIRECTORY, SHOWSEQ, FUNC_CLASS, FUNC_TYPE, WORKFLOW_FLAG, UP_FUNC_CODE, FUNC_DESC, STATUS, MISCFLGS, MISC, ICON_CLS) VALUES ('100404', '批量步骤监控', '/pages/batch/BatchMonitor.jsp', 2, 0, '1004', 4, null, '0', null, null, null, null, null, null, 'fa fa-list-ol');


INSERT INTO IFS_RES_INF (ID, ROLE_ID, FUNCID) VALUES ('bed70b39561c453d956f4f403068edf8', 111, '1004');
INSERT INTO IFS_RES_INF (ID, ROLE_ID, FUNCID) VALUES ('bed70b39561c453d956f4f403068edf9', 111, '100401');
INSERT INTO IFS_RES_INF (ID, ROLE_ID, FUNCID) VALUES ('0f554dc82c4c4b50b3c8c2a5d585b144', 111, '100402');
INSERT INTO IFS_RES_INF (ID, ROLE_ID, FUNCID) VALUES ('b43f0d4516454a67831ad952f4f2b456', 111, '100403');
INSERT INTO IFS_RES_INF (ID, ROLE_ID, FUNCID) VALUES ('b43f0d4516454a67831ad952f4f2b457', 111, '100404');

INSERT INTO IFS_SER_NUM (ID, VALUE_NO, VALUE_INDEX, VALUE_CURR, MAX_VALUE, MIN_VALUE) VALUES ('dadf72b4c6e547d3b3d2f776ee573e3c', 12, '00000000000000000000', 200, 999999999, 1);
--批量运行方式默认为手动，如果调整为自动，需要根据任务参考batch_param.sql调整后执行
INSERT INTO IFS_SYS_PARAM (PARAM_ID, MAGIC_ID, PARAM_START_TM, PARAM_END_TM, PARAM_CHANG_FLAG, PARAM_VALUE_TX, LAST_UPD_TLR, LAST_UPD_FUNC, LAST_UPD_DATE, DESC0, ST, IS_LOCK, IS_DEL) VALUES ('BATH', 'RUN_MODE', null, null, null, '0', null, null, null, '批量运行模式,1:自动运行  0:手工运行', null, null, null);
commit;