drop table IFS_CAL_INF;
drop table IFS_BAT_JOB_INF;
drop table IFS_BAT_PROC_STEP;
drop table IFS_BAT_PROC_LOG;
drop table IFS_BAT_PROC_STATUS;
drop table IFS_BAT_WARNING_LOG;

CREATE TABLE
    IFS_CAL_INF
    (
        ID CHAR(32) NOT NULL,
        YEAR INTEGER,
        HOLIDAY_DEF VARCHAR2(366),
        LAST_UPD_OPER_ID VARCHAR2(32),
        LAST_UPD_TIME CHAR(14),
        PRIMARY KEY (ID)
    );
COMMENT ON TABLE IFS_CAL_INF IS '[框架自带-批量功能]工作日设置表';
COMMENT ON COLUMN IFS_CAL_INF.ID IS '主键';
COMMENT ON COLUMN IFS_CAL_INF.YEAR IS '年份';
COMMENT ON COLUMN IFS_CAL_INF.HOLIDAY_DEF IS '日历字符1工作日0节假日';
COMMENT ON COLUMN IFS_CAL_INF.LAST_UPD_OPER_ID IS '最后更新人';
COMMENT ON COLUMN IFS_CAL_INF.LAST_UPD_TIME IS '最后更新时间';

CREATE TABLE
    IFS_BAT_JOB_INF
    (
        JOBNO INTEGER NOT NULL,
        PRE_JOBNO INTEGER,
        PRE_AUTORUN CHAR(1),
        SYSTEM_TYPE CHAR(2),
        RUNONLINE CHAR(2),
        TIMESTAMPS CHAR(17),
        MISCFLGS VARCHAR2(256),
        MISC VARCHAR2(256),
        PRIMARY KEY (JOBNO)
    );
COMMENT ON TABLE IFS_BAT_JOB_INF IS '[框架自带-批量功能]批量任务表';
COMMENT ON COLUMN IFS_BAT_JOB_INF.JOBNO IS '任务编号';
COMMENT ON COLUMN IFS_BAT_JOB_INF.PRE_JOBNO IS '前置任务编号';
COMMENT ON COLUMN IFS_BAT_JOB_INF.PRE_AUTORUN IS '前置任务是否自动运行1=自动0=不自动';
COMMENT ON COLUMN IFS_BAT_JOB_INF.SYSTEM_TYPE IS '系统类型;与IFS_SYS_INF表中类型SYSTEM_TYPE保持一致，默认1';
COMMENT ON COLUMN IFS_BAT_JOB_INF.RUNONLINE IS '作业是否允许在联机状态下运行0=不允许1=允许2=忽略联机状态';
COMMENT ON COLUMN IFS_BAT_JOB_INF.TIMESTAMPS IS '创建时间';
COMMENT ON COLUMN IFS_BAT_JOB_INF.MISCFLGS IS '扩展字段';
COMMENT ON COLUMN IFS_BAT_JOB_INF.MISC IS '扩展字段(任务描述)';

CREATE TABLE
    IFS_BAT_PROC_STEP
    (
        ID INTEGER NOT NULL,
        JOBNO INTEGER NOT NULL,
        STEP INTEGER NOT NULL,
        SUB_STEP INTEGER NOT NULL,
        PROCESS_FUNCTION VARCHAR2(120) NOT NULL,
        PROCESS_PARAM VARCHAR2(512),
        PROCESS_TLRNO VARCHAR2(20),
        RUNTIME CHAR(2),
        SUB_FLAG CHAR(1),
        MAXPROC INTEGER,
        TEMP_FLAG CHAR(1),
        SUSPEND CHAR(1),
        AUTO CHAR(1),
        TIMESTAMPS CHAR(17),
        DESC0 VARCHAR2(128),
        DESC1 VARCHAR2(1024),
        DESC2 VARCHAR2(1024),
        REPORT_FLAG VARCHAR2(10),
        REPORT_DATA_FLAG CHAR(1),
        REPEAT_CNT INTEGER,
        PRIMARY KEY (ID)
    );
    
COMMENT ON TABLE IFS_BAT_PROC_STEP IS '[框架自带-批量功能]批量任务步骤表';
COMMENT ON COLUMN IFS_BAT_PROC_STEP.ID IS '主键';
COMMENT ON COLUMN IFS_BAT_PROC_STEP.JOBNO IS '任务编号';
COMMENT ON COLUMN IFS_BAT_PROC_STEP.STEP IS '步骤编号';
COMMENT ON COLUMN IFS_BAT_PROC_STEP.SUB_STEP IS '子步骤编号(SUB_FLAG=1;此处使用分行号)';
COMMENT ON COLUMN IFS_BAT_PROC_STEP.PROCESS_FUNCTION IS '批量运行类';
COMMENT ON COLUMN IFS_BAT_PROC_STEP.PROCESS_PARAM IS '运行参数';
COMMENT ON COLUMN IFS_BAT_PROC_STEP.PROCESS_TLRNO IS '批量操作员';
COMMENT ON COLUMN IFS_BAT_PROC_STEP.RUNTIME IS '运行时间9N=不运行90=每天91=每旬(10/20/月底)93=每月末94=每季末95=每半年96=每年41-47对应每周1-7或者为指定每月某天';
COMMENT ON COLUMN IFS_BAT_PROC_STEP.SUB_FLAG IS '是否需要分行并行处理1=是0=否;配合IFS_ORG表BRCLASS=1使用，SUB_STEP等于机构编号';
COMMENT ON COLUMN IFS_BAT_PROC_STEP.MAXPROC IS '该步骤最大运行线程数;默认为3';
COMMENT ON COLUMN IFS_BAT_PROC_STEP.TEMP_FLAG IS '临时监控标志;1=有效0=无效;设置为有效标识该批量子步骤这次不运行';
COMMENT ON COLUMN IFS_BAT_PROC_STEP.SUSPEND IS '批量运行出错可忽略标志1=可忽略0=不可忽略;1表示忽略后继续运行';
COMMENT ON COLUMN IFS_BAT_PROC_STEP.AUTO IS '子步骤是否允许独立运行1=是0=否';
COMMENT ON COLUMN IFS_BAT_PROC_STEP.TIMESTAMPS IS '创建时间';
COMMENT ON COLUMN IFS_BAT_PROC_STEP.DESC0 IS '任务描述';
COMMENT ON COLUMN IFS_BAT_PROC_STEP.DESC1 IS '配合SUB_FLAG使用;过滤不需要处理子步骤号;格式为:!分行号1;分行号2;...';
COMMENT ON COLUMN IFS_BAT_PROC_STEP.DESC2 IS '扩展字段';
COMMENT ON COLUMN IFS_BAT_PROC_STEP.REPORT_FLAG IS '报表功能(暂未使用)';
COMMENT ON COLUMN IFS_BAT_PROC_STEP.REPORT_DATA_FLAG IS '报表功能(暂未使用)';
COMMENT ON COLUMN IFS_BAT_PROC_STEP.REPEAT_CNT IS '批量步骤执行错误重试次数';

CREATE TABLE
    IFS_BAT_PROC_LOG
    (
        ID INTEGER NOT NULL,
        BHDATE CHAR(8) NOT NULL,
        JOBNO INTEGER NOT NULL,
        STEP INTEGER NOT NULL,
        SUB_STEP INTEGER NOT NULL,
        PROCESS_FUNCTION VARCHAR2(120),
        PROCESSID INTEGER,
        START_TIME CHAR(17),
        END_TIME CHAR(17),
        STATUS CHAR(1),
        TIMESTAMPS CHAR(17),
        ERR_MSG VARCHAR2(1024),
        DESC1 VARCHAR2(1024),
        DESC2 VARCHAR2(1024),
        PRIMARY KEY (ID)
    );
COMMENT ON TABLE IFS_BAT_PROC_LOG IS '[框架自带-批量功能]批量运行日志表';
COMMENT ON COLUMN IFS_BAT_PROC_LOG.ID IS '主键';
COMMENT ON COLUMN IFS_BAT_PROC_LOG.BHDATE IS '批量日期';
COMMENT ON COLUMN IFS_BAT_PROC_LOG.JOBNO IS '任务编号';
COMMENT ON COLUMN IFS_BAT_PROC_LOG.STEP IS '步骤编号';
COMMENT ON COLUMN IFS_BAT_PROC_LOG.SUB_STEP IS '子步骤编号';
COMMENT ON COLUMN IFS_BAT_PROC_LOG.PROCESS_FUNCTION IS '批量运行类名称_JOBNO_STEP_SUB_STEP';
COMMENT ON COLUMN IFS_BAT_PROC_LOG.PROCESSID IS '默认0';
COMMENT ON COLUMN IFS_BAT_PROC_LOG.START_TIME IS '开始时间';
COMMENT ON COLUMN IFS_BAT_PROC_LOG.END_TIME IS '结束时间';
COMMENT ON COLUMN IFS_BAT_PROC_LOG.STATUS IS '运行状态0=未运行R=运行中E=已出错F=已完成';
COMMENT ON COLUMN IFS_BAT_PROC_LOG.TIMESTAMPS IS '最后更新时间';
COMMENT ON COLUMN IFS_BAT_PROC_LOG.ERR_MSG IS '错误描述';
COMMENT ON COLUMN IFS_BAT_PROC_LOG.DESC1 IS '异常信息';
COMMENT ON COLUMN IFS_BAT_PROC_LOG.DESC2 IS '预留字段';

CREATE TABLE
    IFS_BAT_PROC_STATUS
    (
        ID INTEGER NOT NULL,
        BHDATE CHAR(8) NOT NULL,
        JOBNO INTEGER NOT NULL,
        STEP INTEGER NOT NULL,
        SUB_STEP INTEGER NOT NULL,
        PROCESS_FUNCTION VARCHAR2(120),
        PROCESSID INTEGER,
        START_TIME CHAR(17),
        END_TIME CHAR(17),
        SUB_FLAG CHAR(1),
        STATUS CHAR(1),
        BRANCHLIST VARCHAR2(1024),
        DESC1 VARCHAR2(1024),
        DESC2 VARCHAR2(1024),
        TIMESTAMPS CHAR(17),
        PRIMARY KEY (ID)
    );
COMMENT ON TABLE IFS_BAT_PROC_STATUS IS '[框架自带-批量功能]批量运行状态表';
COMMENT ON COLUMN IFS_BAT_PROC_STATUS.ID IS '主键';
COMMENT ON COLUMN IFS_BAT_PROC_STATUS.BHDATE IS '批量日期';
COMMENT ON COLUMN IFS_BAT_PROC_STATUS.JOBNO IS '任务编号';
COMMENT ON COLUMN IFS_BAT_PROC_STATUS.STEP IS '步骤编号(最后运行的步骤号)';
COMMENT ON COLUMN IFS_BAT_PROC_STATUS.SUB_STEP IS '子步骤编号;默认0';
COMMENT ON COLUMN IFS_BAT_PROC_STATUS.PROCESS_FUNCTION IS '批量运行类名称_JOBNO_STEP_SUB_STEP;默认空';
COMMENT ON COLUMN IFS_BAT_PROC_STATUS.PROCESSID IS '默认0';
COMMENT ON COLUMN IFS_BAT_PROC_STATUS.START_TIME IS '开始时间';
COMMENT ON COLUMN IFS_BAT_PROC_STATUS.END_TIME IS '结束时间';
COMMENT ON COLUMN IFS_BAT_PROC_STATUS.SUB_FLAG IS '是否分行并行处理1=是0=否;默认1';
COMMENT ON COLUMN IFS_BAT_PROC_STATUS.STATUS IS '运行状态0=未运行R=运行中E=已出错F=已完成';
COMMENT ON COLUMN IFS_BAT_PROC_STATUS.BRANCHLIST IS '分行编号集合;多个逗号分隔';
COMMENT ON COLUMN IFS_BAT_PROC_STATUS.DESC1 IS '预留字段;默认为空';
COMMENT ON COLUMN IFS_BAT_PROC_STATUS.DESC2 IS '预留字段;默认为空';
COMMENT ON COLUMN IFS_BAT_PROC_STATUS.TIMESTAMPS IS '创建时间';

CREATE TABLE
    IFS_BAT_WARNING_LOG
    (
        ID INTEGER NOT NULL,
        TXDATE CHAR(8) NOT NULL,
        JOBNO INTEGER NOT NULL,
        STEP INTEGER NOT NULL,
        SUB_STEP INTEGER NOT NULL,
        CONTRACTNO CHAR(20),
        PERI INTEGER,
        MSG VARCHAR2(1024),
        LINE VARCHAR2(1024),
        TIMESTAMPS CHAR(17),
        PRIMARY KEY (ID)
    );
COMMENT ON TABLE IFS_BAT_WARNING_LOG IS '[框架自带-批量功能]批量运行警告日志表';
COMMENT ON COLUMN IFS_BAT_WARNING_LOG.ID IS  '主键';
COMMENT ON COLUMN IFS_BAT_WARNING_LOG.TXDATE IS  '批量日期';
COMMENT ON COLUMN IFS_BAT_WARNING_LOG.JOBNO IS  '任务编号';
COMMENT ON COLUMN IFS_BAT_WARNING_LOG.STEP IS  '步骤编号';
COMMENT ON COLUMN IFS_BAT_WARNING_LOG.SUB_STEP IS  '子步骤编号';
COMMENT ON COLUMN IFS_BAT_WARNING_LOG.CONTRACTNO IS  '默认空';
COMMENT ON COLUMN IFS_BAT_WARNING_LOG.PERI IS  '剩余重试次数;默认-1';
COMMENT ON COLUMN IFS_BAT_WARNING_LOG.MSG IS  '警告描述';
COMMENT ON COLUMN IFS_BAT_WARNING_LOG.LINE IS  '异常信息';
COMMENT ON COLUMN IFS_BAT_WARNING_LOG.TIMESTAMPS IS  '创建时间';
    
    
CREATE UNIQUE INDEX IDX_IFS_CAL_INF_0 ON IFS_CAL_INF (YEAR);
CREATE UNIQUE INDEX IDX_IFS_BAT_PROC_LOG_0 ON IFS_BAT_PROC_LOG (BHDATE, JOBNO, STEP, SUB_STEP);
CREATE UNIQUE INDEX IDX_IFS_BAT_PROC_STATUS_0 ON IFS_BAT_PROC_STATUS (BHDATE, JOBNO);

CREATE SEQUENCE SEQ_IFS_BAT_PROC_LOG INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999 MINVALUE 1 NOCYCLE CACHE 20 ORDER;
CREATE SEQUENCE SEQ_IFS_BAT_PROC_STATUS INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999 MINVALUE 1 NOCYCLE CACHE 20 ORDER;
CREATE SEQUENCE SEQ_IFS_BAT_WARNING_LOG INCREMENT BY 1 START WITH 1 MAXVALUE 99999999999 MINVALUE 1 NOCYCLE CACHE 20 ORDER;