drop table IFS_NATION_INF;
drop table IFS_CUR_INF;
drop table IFS_CUR_RATE;

CREATE TABLE
    IFS_NATION_INF
    (
        NATIONREGION_CODE VARCHAR2(10) NOT NULL,
        CHINA_NAME VARCHAR2(128),
        NATIONREGION_NUMBER VARCHAR2(10),
        CHINA_SHORT_NAME VARCHAR2(128),
        ENG_NAME VARCHAR2(128),
        ENG_SHORT_NAME VARCHAR2(128),
        ST CHAR(1),
        IS_LOCK CHAR(1),
        IS_DEL CHAR(1),
        CRT_DT CHAR(8),
        LAST_UPD_TMS VARCHAR2(14),
        LAST_UPD_OPER VARCHAR2(20),
        PRIMARY KEY (NATIONREGION_CODE)
    );

COMMENT ON TABLE IFS_NATION_INF IS '[框架自带-辅助功能]国家地区表';
COMMENT ON COLUMN IFS_NATION_INF.NATIONREGION_CODE IS '国家/地区代码';
COMMENT ON COLUMN IFS_NATION_INF.CHINA_NAME IS '中文全称';
COMMENT ON COLUMN IFS_NATION_INF.NATIONREGION_NUMBER IS '国家/地区数字代码';
COMMENT ON COLUMN IFS_NATION_INF.CHINA_SHORT_NAME IS '中文简称';
COMMENT ON COLUMN IFS_NATION_INF.ENG_NAME IS '英文全称';
COMMENT ON COLUMN IFS_NATION_INF.ENG_SHORT_NAME IS '英文简称';
COMMENT ON COLUMN IFS_NATION_INF.ST IS '记录状态(暂未使用)';
COMMENT ON COLUMN IFS_NATION_INF.IS_LOCK IS '是否锁定(暂未使用)';
COMMENT ON COLUMN IFS_NATION_INF.IS_DEL IS '是否删除(暂未使用)';
COMMENT ON COLUMN IFS_NATION_INF.CRT_DT IS '创建日期';
COMMENT ON COLUMN IFS_NATION_INF.LAST_UPD_TMS IS '最后更新时间';
COMMENT ON COLUMN IFS_NATION_INF.LAST_UPD_OPER IS '最后更新人';

CREATE TABLE
    IFS_CUR_INF
    (
        CURCD VARCHAR2(6) NOT NULL,
        CNNAME VARCHAR2(52),
        ST CHAR(1),
        IS_LOCK CHAR(1),
        IS_DEL CHAR(1),
        CREATE_DATE CHAR(8),
        LAST_UPD_DATE CHAR(8),
        LAST_UPD_TLR VARCHAR2(20),
        SHOWSEQ NUMBER(22),
        ISUSD CHAR(1),
        ENNAME VARCHAR2(20),
        CURSYMBOL VARCHAR2(20),
        CREATE_TLR VARCHAR2(20),
        BASE_UNIT VARCHAR2(4),
        MIN_UNIT VARCHAR2(4),
        CUR_EDICD CHAR(3),
        CUR_EDINAME VARCHAR2(25),
        CURNO VARCHAR2(6),
        DRATEDAYS CHAR(1),
        PRIMARY KEY (CURCD)
    );
COMMENT ON TABLE IFS_CUR_INF IS '[框架自带-辅助功能]币种信息表';
COMMENT ON COLUMN IFS_CUR_INF.CURCD IS '币种货币代码';
COMMENT ON COLUMN IFS_CUR_INF.CNNAME IS '币种中文名称';
COMMENT ON COLUMN IFS_CUR_INF.ST IS '记录状态(暂未使用)';
COMMENT ON COLUMN IFS_CUR_INF.IS_LOCK IS '是否锁定(暂未使用)';
COMMENT ON COLUMN IFS_CUR_INF.IS_DEL IS '是否删除(暂未使用)';
COMMENT ON COLUMN IFS_CUR_INF.CREATE_DATE IS '创建日期';
COMMENT ON COLUMN IFS_CUR_INF.LAST_UPD_DATE IS '最后更新日期';
COMMENT ON COLUMN IFS_CUR_INF.LAST_UPD_TLR IS '最后更新人';
COMMENT ON COLUMN IFS_CUR_INF.SHOWSEQ IS '显示顺序';
COMMENT ON COLUMN IFS_CUR_INF.ISUSD IS '是否使用1是0否';
COMMENT ON COLUMN IFS_CUR_INF.ENNAME IS '币种英文名称';
COMMENT ON COLUMN IFS_CUR_INF.CURSYMBOL IS '币种符号';
COMMENT ON COLUMN IFS_CUR_INF.CREATE_TLR IS '创建人员';
COMMENT ON COLUMN IFS_CUR_INF.BASE_UNIT IS '基本单位';
COMMENT ON COLUMN IFS_CUR_INF.MIN_UNIT IS '最小单位';
COMMENT ON COLUMN IFS_CUR_INF.CUR_EDICD IS 'EDI币种代码';
COMMENT ON COLUMN IFS_CUR_INF.CUR_EDINAME IS 'EDI币种名称';
COMMENT ON COLUMN IFS_CUR_INF.CURNO IS '外部币种代码';
COMMENT ON COLUMN IFS_CUR_INF.DRATEDAYS IS '日利息计算天数DDIC360';

CREATE TABLE
    IFS_CUR_RATE
    (
        ID VARCHAR2(32) NOT NULL,
        CURCD CHAR(3) NOT NULL,
        CURRRATE_DATE CHAR(8) NOT NULL,
        LAST_UPD_DATE CHAR(8),
        LAST_UPD_TLR VARCHAR2(8),
        TO_CURCD CHAR(3) NOT NULL,
        BUY_RATE NUMBER(16,3),
        SELL_RATE NUMBER(16,3),
        EXCHG_RATE NUMBER(16,3),
        PRIMARY KEY (ID)
    );
COMMENT ON TABLE IFS_CUR_RATE IS '[框架自带-辅助功能]币种汇率信息表';
COMMENT ON COLUMN IFS_CUR_RATE.ID IS '主键';
COMMENT ON COLUMN IFS_CUR_RATE.CURCD IS '币种';
COMMENT ON COLUMN IFS_CUR_RATE.CURRRATE_DATE IS '汇率日期';
COMMENT ON COLUMN IFS_CUR_RATE.LAST_UPD_DATE IS '最后更新日期';
COMMENT ON COLUMN IFS_CUR_RATE.LAST_UPD_TLR IS '最后更新人';
COMMENT ON COLUMN IFS_CUR_RATE.TO_CURCD IS '兑换币种';
COMMENT ON COLUMN IFS_CUR_RATE.BUY_RATE IS '买入价';
COMMENT ON COLUMN IFS_CUR_RATE.SELL_RATE IS '卖出价';
COMMENT ON COLUMN IFS_CUR_RATE.EXCHG_RATE IS '中间价';